### ISSUE TITLE
cc应用层防护的js跳转，setcookie是默认开启的是吗，具体代码实现在什么地方？

### ISSUE THREAD

**Issue by gaoshunsheng** [starjun/openstar#1]

**Comment by starjun** [comment]
js跳转 : 使用rehtml , refile, relua  （不建议在body阶段进行内容替换）自行写一些跳转代码（自己可以写出各种猥琐js，发挥想象把）
set-cookie：在多次CC防护实战中，效果不行（代码以前就写好了，给删了），现在把这一块代码加上去了，是rewrite_Mod 模块中进行配置，

**Comment by Gitzhaoyang** [comment]
请问cookie为什么只在rewrite_mod阶段配置,  具体的验证没有么?

**Comment by starjun** [comment]
rewrite_Mod 是用于跳转使用的，set-cookie后，有判断，cookie中有和合法的token就继续，没有就继续跳转。 cookie防止采集 效果有限。
