### ISSUE TITLE
openstar/lib/optl.lua:481: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by recrute** [starjun/openstar#13]
```
2017/09/22 16:07:24 [error] 12373#12373: *350 lua entry thread aborted: runtime error: ~/openresty/openstar/lib/optl.lua:481: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	~/openresty/openstar/lib/optl.lua:481: in function 'get_table'
	~/openresty/openstar/access_all.lua:46: in function <~/openresty/openstar/access_all.lua:1>, client: 192.168.*.*, server: *.*.cn, request: "POST *.*?action=save HTTP
```

**Comment by recrute** [comment]
没看过 lua 的脚本，最终临时在 lib/optl.lua:get_table 中做了如下改动：

# **if _tb then**
			for k,v in pairs(_tb) do
				if type(v) == "table" then
					local tmp_v = {}
					for i,vv in ipairs(v) do
						if vv == true then
							vv=""
						end
						table.insert(tmp_v,vv)
					end
					v = table.concat(tmp_v,",")
				elseif v == true then
					v= ""
				end
				table.insert(tb_args,v)
			end
# 		**end**

**Comment by starjun** [comment]
请问 POST 内容是啥子，可以发来看看么

**Comment by recrute** [comment]
暂时不太方便重现问题，有可能是跟提交的数据超过 client_max_body_size 配置的值有关系。

**Comment by starjun** [comment]
更新处理该bug了
