### ISSUE TITLE
咨询几个问题

### ISSUE THREAD

**Issue by kame000** [starjun/openstar#16]
首先，感谢分享的知识。
我大概看了下，没理解。

我对于楼的项目关注点在 CC防护上面。

之前用过一个开源版本使用的 Httpguard 防护CC的不过code太老了，自己想重写，但是又没那么多时间去搞这个东西，lua语言使用也是一知半解。
主要想问楼主两个问题：
1，代码是否一直开源？
2，github上的代码是否会一直维护？
3，是否可以写一个使用文档文档详解
4，Read 里面写的确实比较乱，最好有个清晰的结构看来比较容易。希望能改进下

**Comment by starjun** [comment]
敬请期待，
