### ISSUE TITLE
http v2 not supported yet

### ISSUE THREAD

**Issue by ouwsh** [starjun/openstar#17]
nginx 的error.log 显示出错如下：

[C]: in function 'raw_header'
/opt/openresty/openstar/access_all.lua:32: in function </opt/openresty/openstar/access_all.lua:1>, client: 110.81.7.88, server: _, request: "GET /favicon.ico HTTP/2.0", host: "179.226.234.102", referrer: "https://179.226.234.102/index.html"
2017/11/11 12:31:16 [error] 20108#0: *9095 lua entry thread aborted: runtime error: /opt/openresty/openstar/access_all.lua:32: http v2 not supported yet
stack traceback:
coroutine 0:

您好，现在http2应用挺广了。openstar要怎么样才可以支持http2呢？

**Comment by starjun** [comment]
注释掉access_all.lua文件中
local headers_data = ngx_unescape_uri(ngx.req.raw_header(false))
http2中没有这个api,先临时这么处理下，后续代码我会做异常处理

**Comment by ouwsh** [comment]
哦。感谢您回复。
另外我想咨询下：
如果注释掉local headers_data = ngx_unescape_uri(ngx.req.raw_header(false))
这一行，是否会对OpenStar的防护功能，例如防cc防注入这些功能有影响呢？

**Comment by starjun** [comment]
不会，headers_data 这个是取整个http头数据的函数 注入等一些过滤点 基本在args 和 post 内容中，一般不会在 headers_data 进行过滤，所以放心注释，现在已经更新代码进行异常处理了。

**Comment by ouwsh** [comment]
https://github.com/openresty/lua-nginx-module/issues/1186#issuecomment-343682110
我也问了章哥，他在最后回复有个建议。不知是否有帮助。您看看

**Comment by starjun** [comment]
ngx.req.raw_header 在http v2.0 下不支持

**Comment by ouwsh** [comment]
好的，非常感谢
