### ISSUE TITLE
用io.open写拦截日志问题

### ISSUE THREAD

**Issue by JoyChou93** [starjun/openstar#18]
io.open会产生阻塞，如果在高并发的情况下，用io.open效果肯定不好。
有考虑有其他的方式么？比如socket？

**Comment by starjun** [comment]
可以自己测试下，动手实践比猜测好

**Comment by JoyChou93** [comment]
测试了，发现用io.open比socket会稍微慢一点。
试想一个场景，如果在高并发的写日志过程中，访问正常页面，速度会不会影响？我测试后，影响并不大，我在思考为什么？

**Comment by starjun** [comment]
记录日志和执行阶段是有关系的，io.open 放到log阶段去写日志 和access阶段 是不一样的，我用思博伦打的并发测试，io.open 性能很高，比socket高太多。你可以在测试一下

**Comment by linger118927** [comment]
不能够吧，io.open比socket高，如果socket是阻塞模式的那肯定高，虽然现在大多数开源的项目用的都是本地log记录的方式，但是经过测试，跟 非阻塞方式的socket方式记录log比还是慢的
