### ISSUE TITLE
实践过程中的几个问题>

### ISSUE THREAD

**Issue by Gitzhaoyang** [starjun/openstar#2]
自己在实践过程中学习到了很多.
因为我是新人, 所以有些问题不太懂

比如在单机/集群那里
1. "保存了config.json内容，和conf_json目录下所有规则的json文件，以及拦截记录的计数（如host/method拦截计数）。"
这些操作具体在什么时候完成呢? 需要自己写定时脚本访问api/redis.lua吗>
另外, 我发现,  ip_Mod中的ip信息并没有保存到redis,出于什么考虑呢?

2.  对于日志, 是否还有可以完善的地方? 如果在集群模式下, 我们应该怎么收集所有机器的日志并统一呢? 

3. 针对cc deny那边, 只在单位时间内访问次数限制,然后拉黑
假如有人周期性的访问某个接口, 比如每天, 每个星期, 定期访问某个接口, 我们应该如何发现, 并对这种行为进行阻止呢?能否简单提供一下思路>

感激不尽

**Comment by starjun** [comment]
1.同步到redis需要自己主动推送，没有写被动定时推送
2.ip_Mod推送到redis还没写
3.业务接口更具自己的情况，做验证，ip和key啥的进行绑定，参考微软/aws的接口就行了，如果是公共接口（非申请接入的）就做访问频率的限制，其实还可以在细分，接口是给浏览器调用的还是应用调用的，浏览器的话可以增加JS跳转等等操作，做一些加密等增加攻击成本等，剩下就做频率、总数的限制，发现问题通过日志分析就行了。

**Comment by Gitzhaoyang** [comment]
您现在的redis同步我看都是全量的, 代价是不是有点大, 是否有考虑做成增量的, 是否ip_Mod没写在考虑增量?

而且我看您在api/ip_dict.lua中 , 只做了nginx.shared.ip_dict的修改, 然而相关文件(conf/ip_Mod.json)并没有同步修改.会完善吗?
