### ISSUE TITLE
realIpFrom_Mod字段名包含下划线时无法匹配

### ISSUE THREAD

**Issue by nobodysz** [starjun/openstar#20]
如header中真实字段名为real_ip(包含下划线时)，无法匹配改真实ip字段

{
    "localhost": {
        "ips": ["*",""],
        "realipfrom": "real_ip"
    }
}

该规则匹配header中的 real-ip(中划线)，那么如何匹配带下划线的header字段呢？

**Comment by starjun** [comment]
underscores_in_headers nginx 配置查这个

**Comment by starjun** [comment]
官方都不建议使用 _ ，并且定义为不合法的头 还是不要用 下划线了。
