### ISSUE TITLE
上传和图片木马规则

### ISSUE THREAD

**Issue by m1911** [starjun/openstar#24]
能不能给个上传和图片木马规则的示例，参考app那里面的示例不会弄。
谢谢

**Comment by starjun** [comment]
{
        "state": "on",
        "id":"11-test-post_form",
        "action": "deny",
        "post_form":1024,
       -- 每个参数的长度 
        "hostname": ["localhost5460",""],
        "uri": ["/api/test/debug",""],
        "app_ext":[
        ["post_form",["\\.(jpg|jpeg|png|webp|gif)$","jio",["image0",2],true],"or"],
        -- 表单 name 为image0 的过滤
        ["post_form",["(;|-|/)","jio",["image0",2],false],"or"]
        ]
    }

这个是例子 自己研究一下，用，试 ！
还有可以通过 post_all 对整个post的body体使用正则来过滤
