### ISSUE TITLE
开启openstar后nginx内存占用持续升高

### ISSUE THREAD

**Issue by stutimes** [starjun/openstar#29]
不知道是不是个例，在开启openstar后，nginx内存占用百分比持续升高，直到系统崩溃。。。关闭后，nginx内存占用趋于稳定

背景:站点一直有垃圾蜘蛛频繁访问，为节省宽带，使用了openstar，并用了ua策略，但是开启之后过几分钟站点访问速度明显减慢，nginx内存持续上升，经一段时间观察测试，发现以上问题。不知道是不是个例。。。

**Comment by starjun** [comment]
信息太少了，不知道怎么查找原因了，启用一下network_Mod 做好频率限制吧，在看看 nginx 错误日志，
openstar 主要消耗 CPU 和 内存, 但是都没有出现崩溃的情况，是不是被CC 攻击，现象是连接服务器都慢，操作服务器都卡

**Comment by stutimes** [comment]
"Author "<author@noreply.github.com>;
主题：Re: [starjun/openstar] 开启openstar后nginx内存占用持续升高 (#29)
-----------------------------------

 
Closed #29.
