### ISSUE TITLE
redis增量问题, 文件更新问题

### ISSUE THREAD

**Issue by Gitzhaoyang** [starjun/openstar#3]
您现在的redis同步我看是全量的, 代价是不是有点大, 是否有考虑做成增量的, 是否ip_Mod考虑增量?

而且我看您在api/ip_dict.lua中 , 只做了nginx.shared.ip_dict的修改, 然而相关文件(conf/ip_Mod.json)并没有同步修改.会完善吗?

**Comment by starjun** [comment]
1：后面有时间在改增量同步
2：还是那个ip封闭时间问题，还没想好怎么解决，永久的ip黑/白名单好整，那种动态产生的ip，以及封锁时间设置多少秒的，这个就麻烦了，暂没想好怎么解决这个问题。

**Comment by Gitzhaoyang** [comment]
redis 也可以设置expire time的, 具体: http://redisdoc.com/key/ttl.html

**Comment by starjun** [comment]
3Q，正在考虑增加这个功能。关于增量推送到redis有好的建议么?

**Comment by Gitzhaoyang** [comment]
我现在考虑的是, 
1. ip和统计数据比较大, 本地就不存了, 直接只存redis
2. 关于配置像, 每次人为修改调用api可以先只更新redis, 然后在init_worker_by_lua*中调用ngx.timer.at(interval, func()) 几十秒全量更新下本地
