### ISSUE TITLE
怎么过滤post请求中json格式的内容？

### ISSUE THREAD

**Issue by JoysCode** [starjun/openstar#35]
怎么过滤post请求中json格式的内容？比如{"xx":"xx";"hacker":''zz''}，我要过滤"hacker"字眼。

**Comment by starjun** [comment]
在 access_all.lua `if method == "POST" and http_content_type then` 后面增加一行代码
`posts_all = ngx.req.get_body_data()` 这个是取 client_body_buffer_size 以内的大小的body 内容
`posts_all = optl.get_post_all()` 这个是取 client_max_body_size 大小的内容
根据情况 添加代码， 建议用第一个

下面就是添加规则 app_Mod or  host_Mod/xxx.json

app_ext规则

"app_ext":[
        ["post_all",["hacker","in"],"or"]
        ]

["hacker","in"] 这里可以使用其他的匹配方式，等于 包含 数组 等
