### ISSUE TITLE
使用中的小问题

### ISSUE THREAD

**Issue by lupus721** [starjun/openstar#38]
使用中在访问kinbana的时候有页面被拦截了
`HTTP/1.1 403 /api/saved_objects/_find?type=dashboard&per_page=1000&page=1&search_fields=title^3&search_fields=description Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36  waf_log: [args_HPP] deny No: 0 
`
没有找到args_HPP对应的规则，求教下。

还有就是如何对某个路径白名单，比如/api/saved_objects/这个路径后面所有的请求都放过

**Comment by lupus721** [comment]
已经把 app_Mod.json 中的api相关的都删除了。。

**Comment by lupus721** [comment]
找到问题了
search_fields=title^3&search_fields=description
这部分触发了请求参数污染攻击args_HPP
在base.json里关闭了，，，就好了

**Comment by starjun** [comment]
https://www.kancloud.cn/openstar/install/1136671
个人用户可以使用这个带界面的商业版本， 个人使用同样是免费的～

**Comment by lupus721** [comment]
> https://www.kancloud.cn/openstar/install/1136671
> 个人用户可以使用这个带界面的商业版本， 个人使用同样是免费的～

好的，回来试试
