### ISSUE TITLE
openstar/access_all.lua:559: bad argument #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by Spadeslyn** [starjun/openstar#40]
9994#0: *54544 lua entry thread aborted: runtime error: /opt/openresty/openstar/access_all.lua:559: bad argument #1 to 'pairs' (table expected, got nil)

nginx version: openresty/1.15.8.1

**Comment by starjun** [comment]
非常感谢已经定位的问题，且已经修复了，是 get_post_args() 函数取值为 nil , 超出 
 client_body_buffer_size 大小...
