### ISSUE TITLE
attempt to index local 'optl' (a userdata value)

### ISSUE THREAD

**Issue by lazyman01** [starjun/openstar#49]
用脚本安装完后一直报这个，请问是什么原因
2020/10/20 23:15:47 [error] 70063#0: *884 lua entry thread aborted: runtime error: /opt/openresty/openstar/i_worker.lua:130: attempt to index local 'optl' (a userdata value)
stack traceback:
coroutine 0:
	/opt/openresty/openstar/i_worker.lua: in function </opt/openresty/openstar/i_worker.lua:127>, context: ngx.timer

**Comment by lazyman01** [comment]
so库文件没包含进去导致的

**Comment by Microbenefits** [comment]
@lazyman01 我也遇到了同样的报错，请问你是怎么解决的？
