### ISSUE TITLE
使用bash下的脚本安装openstar后访问提示500

### ISSUE THREAD

**Issue by Microbenefits** [starjun/openstar#50]
openresty版本，1.17.8.2
curl http://127.0.0.1,返回500 Internal Server Error
nginx errorlog如下
报错如下：coroutine 0:
	/opt/openresty/openstar/i_worker.lua: in function </opt/openresty/openstar/i_worker.lua:127>, context: ngx.timer
2020/12/02 15:54:51 [error] 29#0: *1819 lua entry thread aborted: runtime error: /opt/openresty/openstar/i_worker.lua:130: attempt to index local 'optl' (a userdata value)
stack traceback:

**Comment by starjun** [comment]
openstar 的路径一定要正确，/opt/openresty/openstar
你看看 /opt/openresty/openstar/lib/optl.lua 这个文件存在不

**Comment by Microbenefits** [comment]
openstar路径是正确的，optl.lua这个文件也是存在的。手动安装和脚本安装都试了，都是报这个错

**Comment by starjun** [comment]
waf.conf
这个文件里面的  lua_package 检查一下

**Comment by Microbenefits** [comment]
lua_package_path "/opt/openresty/openstar/lib/?.lua;/opt/openresty/lualib/?.lua";
我看有个网友遇到了同样的问题，说是so库没包含进去，不懂啥意思

**Comment by starjun** [comment]
lua_package_cpath "/opt/openresty/openstar/lib/?.so;;"; 打开

**Comment by Microbenefits** [comment]
搞定了，谢谢，这行默认注释掉了
