### ISSUE TITLE
curl 127.0.0.1:5460 报错

### ISSUE THREAD

**Issue by llzzii** [starjun/openstar#53]
报错信息如下：
```
*1767 lua entry thread aborted: runtime error: /opt/openresty/openstar/i_worker.lua:130: attempt to index local 'optl' (a userdata value)
stack traceback:
coroutine 0:
        /opt/openresty/openstar/i_worker.lua: in function </opt/openresty/openstar/i_worker.lua:127>, context: ngx.timer

```

1、openstar 的路径正确，/opt/openresty/openstar
2、/opt/openresty/openstar/lib/optl.lua 这个文件存在
3、waf.conf 中lua_package_cpath "/opt/openresty/openstar/lib/?.so;;";  这行也没有注释；

但还是报上面的错误

**Comment by charnet1019** [comment]
+1

openresty 版本: 1.19.3.1

![image](https://user-images.githubusercontent.com/18616254/119638317-1dfde280-be49-11eb-8b54-923037d5d6a3.png)

**Comment by starjun** [comment]
openresty 安装路径 /opt/openresty/

**Comment by charnet1019** [comment]
> openresty 安装路径 /opt/openresty/

和路径没有关系吧， 已经把对应的路径修改为openresty安装的路径(/usr/local/openresty/)了

**Comment by starjun** [comment]
请更新一下，找到原因了，是少引用了一个库 ipmatcher

**Comment by charnet1019** [comment]
> 请更新一下，找到原因了，是少引用了一个库 ipmatcher

可以了，多谢

**Comment by charnet1019** [comment]
> 请更新一下，找到原因了，是少引用了一个库 ipmatcher


这个是否有影响？
![image](https://user-images.githubusercontent.com/18616254/119754947-c8bae300-bed3-11eb-937b-468bf82fa0ab.png)

**Comment by charnet1019** [comment]
> > 请更新一下，找到原因了，是少引用了一个库 ipmatcher
> 
> 这个是否有影响？
> ![image](https://user-images.githubusercontent.com/18616254/119754947-c8bae300-bed3-11eb-937b-468bf82fa0ab.png)

![image](https://user-images.githubusercontent.com/18616254/119762031-87c8cb80-bedf-11eb-85d8-6cd0f9431206.png)
这个配置中文后在浏览器显示乱码
