### ISSUE TITLE
功能改进

### ISSUE THREAD

**Issue by xuanyuanaosheng** [starjun/openstar#54]
1.   建议增加ModSecurity，并使用ModSecurity-nginx将ModSecurity安装为OpenResty的模块

2.   建议更新 openresty 里面的 opm 版本：https://opm.openresty.org/package/starjun/openstar/

3.   建议提供一些开源的 waf 相关的特征库

4.   能否提供商业版本的demo

**Comment by starjun** [comment]
可以集成 ModSecurity 但是没有必要，你自己搭建用起来就知道了，误报和规则的维护比我现在设计的麻烦多了
opm 目前不好支持，需要编译 nginx 模块，最好还是手动编译安装
特征库我这就不提供了，百度一下
商业版的需要自己使用虚机搭建起来，目前个人、企业使用都是免费，只有技术支持收费（新调整的界面还没有完全 OK）

**Comment by xuanyuanaosheng** [comment]
我看官方的opm有您的项目了，不打算维护更新下了？

特征库对于收费项目还是有必要的。

@starjun  我搭建企业版本试试看
