### ISSUE TITLE
对于盲命令执行，大佬如何做检测的

### ISSUE THREAD

**Issue by ghost** [starjun/openstar#55]
打字

**Comment by starjun** [comment]
1：提取特征 使用字符串各种匹配方式进行匹配
2：使用高级规则进行规则的组合匹配（同一个匹配位置也可以规则组进行组合匹配）
3：使用高级规则使用 lua 代码进行过滤（代码可以实现自己想要的更复杂过滤）
4：使用mirror后，依赖请求分析的大数据，延后处理
5：业务上对接口实现防重放设计配合WAF网关进行联动拦截
...
