### ISSUE TITLE
4层代理-转发配置-stream配置无法保存

### ISSUE THREAD

**Issue by luckykeeper** [starjun/openstar#57]
CentOS Linux release 7.9.2009 (Core) x64 openresty版，已经配置完成redis，授权认证显示正常，安装脚本显示

 >ngx  版本: openresty/1.19.9.1
 >nginx path 状态: 已配置
> openstar   版本: 2.5.10
> luarocks   版本: 3.2.1
> luarocks  软连接建立:/usr/bin/luarocks
> 当前操作系统：[centos]
> 版本号：[7] 位数：[x64]

stream文件模板没有修改，如下
```

upstream {{stream_name}} {
    #server 13.7.42.92 weight=5 max_fails=1 fail_timeout=10s;
    #server 13.7.42.91 weight=5 max_fails=1 fail_timeout=10s;
    {% for _, v in ipairs(ips) do %}
    server {{v.server}}{%if v.weight then%} weight={{v.weight}}{%end%} max_fails={{v.max_fails or 1}} fail_timeout={{v.fail_timeout or "10s"}};
    {% end %}
    }

server {
    listen       {{port}} {% if l_type == "udp" then %} {{l_type}} {% end %};
    proxy_connect_timeout {{proxy_connect_timeout}};
    proxy_timeout {{proxy_timeout}};
    proxy_pass {{stream_name}};

}
```

配置截图如下
![捕获](https://user-images.githubusercontent.com/34579433/160520997-6a97991e-6196-4b85-88be-d18ec8273647.PNG)

提交后提示
成功
stream add success
但是没有数据，表格依然是No Data
请问是我哪里配置不对吗？

**Comment by starjun** [comment]
http 协议的 使用 域名方式添加
stream 针对非 http 类使用的，直接加群进行咨询，邮件基本很少用

Luckykeeper ***@***.***> 於 2022年3月29日 週二 上午10:34寫道：

**Comment by luckykeeper** [comment]
好的，我复查了一下，其实就是上面的时间没加s ，加上就有了233，得写成“5s”这样的，感谢回复
